name: Run Web Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (adjust as needed)
  workflow_dispatch:  # Enables manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2

      - name: Build Docker image
        run: docker build -t web-scraper .

      - name: Run Docker container and save data
        run: |
          mkdir -p output_data
          docker run -v $(pwd)/output_data:/data web-scraper

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        with:
          name: "scraped-data-${{ env.CURRENT_DATE }}"
          path: output_data/*.csv
