name: Run Web Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (adjust as needed)
  workflow_dispatch:  # Enables manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2

      - name: Build and run Docker container
        run: |
          docker build -t web-scraper .
          docker run web-scraper
